/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.35
 * Generated at: 2019-04-26 08:49:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import in.co.sunrays.proj4.util.HTMLUtility;
import in.co.sunrays.proj4.model.TimeTableModel;
import in.co.sunrays.proj4.controller.TimeTableCtl;
import in.co.sunrays.proj4.controller.ORSView;
import in.co.sunrays.proj4.controller.TimeTableListCtl;
import in.co.sunrays.proj4.bean.TimeTableBean;
import in.co.sunrays.proj4.bean.CoursesBean;
import in.co.sunrays.proj4.util.ServletUtility;
import in.co.sunrays.proj4.util.DataUtility;
import java.util.List;
import java.util.Iterator;
import java.util.HashMap;
import javax.servlet.ServletContext;
import in.co.sunrays.proj4.bean.RoleBean;
import in.co.sunrays.proj4.controller.LoginCtl;
import in.co.sunrays.proj4.bean.UserBean;
import in.co.sunrays.proj4.controller.ORSView;

public final class TimeTableListView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/jsp/Footer.jsp", Long.valueOf(1554292396781L));
    _jspx_dependants.put("/jsp/Header.jsp", Long.valueOf(1555328989969L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("in.co.sunrays.proj4.controller.TimeTableListCtl");
    _jspx_imports_classes.add("in.co.sunrays.proj4.model.TimeTableModel");
    _jspx_imports_classes.add("in.co.sunrays.proj4.util.HTMLUtility");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("in.co.sunrays.proj4.controller.TimeTableCtl");
    _jspx_imports_classes.add("in.co.sunrays.proj4.bean.CoursesBean");
    _jspx_imports_classes.add("in.co.sunrays.proj4.controller.ORSView");
    _jspx_imports_classes.add("in.co.sunrays.proj4.bean.RoleBean");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("in.co.sunrays.proj4.bean.TimeTableBean");
    _jspx_imports_classes.add("in.co.sunrays.proj4.controller.LoginCtl");
    _jspx_imports_classes.add("in.co.sunrays.proj4.util.ServletUtility");
    _jspx_imports_classes.add("javax.servlet.ServletContext");
    _jspx_imports_classes.add("in.co.sunrays.proj4.bean.UserBean");
    _jspx_imports_classes.add("in.co.sunrays.proj4.util.DataUtility");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(ORSView.APP_CONTEXT);
      out.write("/js/jquery-ui.css\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(ORSView.APP_CONTEXT);
      out.write("/js/calendar.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(ORSView.APP_CONTEXT);
      out.write("/js/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(ORSView.APP_CONTEXT);
      out.write("/js/jquery-ui.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com//jquery-1.12.4.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function noSunday(date){\r\n");
      out.write("\treturn [date.getDay()==0 ? false:true]\r\n");
      out.write("};\r\n");
      out.write("$(function(){\r\n");
      out.write("\t$(\"#date\").datepicker({\r\n");
      out.write("\t\tchangeMonth:true,\r\n");
      out.write("\t\tchangeYear:true,\r\n");
      out.write("\t\t//maxDate:100,\r\n");
      out.write("\t\t//maxYear:2,\r\n");
      out.write("\t\t//minDate: 0,\r\n");
      out.write("\t\tbeforeShowDay:noSunday,\r\n");
      out.write("\t\t//beforeShowDay1: noSunday1,\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tyearRange:\"-0:+1\"\r\n");
      out.write("\t\t//yearRange:\"+10:\"\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//defaultDate:\"01/01/1999\"\r\n");
      out.write("\t});\t\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function checkedAll()\r\n");
      out.write("{\r\n");
      out.write("\t\r\n");
      out.write("\tvar totalElement=document.forms[0].elements.length;\r\n");
      out.write("\tfor(var i=0;i<totalElement;i++){\r\n");
      out.write("\t\tvar en=document.forms[0].elements[i].name;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(en!=undefined & en.indexOf(\"chk_\")!=-1)\r\n");
      out.write("\t\t{\t\r\n");
      out.write("\t\t\tdocument.forms[0].elements[i].checked=document.frm.chk_all.checked;\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t}\t\t\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function check(){\r\n");
      out.write("\tvar en=document.forms[0].elements[6].name;\r\n");
      out.write("\tif(en!=undefined & en.indexOf(\"chk_\")!=-1)\r\n");
      out.write("\t{\t\r\n");
      out.write("\t\tdocument.forms[0].elements[6].checked=document.frm.chk_all.unchecked;\r\n");
      out.write("\t}\t\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../format.css\"></link>\r\n");
      out.write("</head>\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    UserBean userBean = (UserBean) session.getAttribute("user");

    boolean userLoggedIn = userBean != null;

    String welcomeMsg = "Hi, ";

    if (userLoggedIn) {
        String role = (String) session.getAttribute("role");
        welcomeMsg += userBean.getFirstName() + " (" + role + ")";
    } else {
        welcomeMsg += "Guest";
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" border=\"0\" bgcolor=\"lightgrey\">\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td width=\"90%\" ><a href=\"");
      out.print(ORSView.WELCOME_CTL);
      out.write("\">Welcome</b></a> |\r\n");
      out.write("            ");

            if (userLoggedIn) {
        
      out.write(" <a href=\"");
      out.print(ORSView.LOGIN_CTL);
      out.write("?operation=");
      out.print(LoginCtl.OP_LOG_OUT);
      out.write("\">Logout</b></a>\r\n");
      out.write("\r\n");
      out.write("            ");

                } else {
            
      out.write(" <a href=\"");
      out.print(ORSView.LOGIN_CTL);
      out.write("\">Login</b></a> ");

     }
 
      out.write("</td>\r\n");
      out.write("        <td rowspan=\"2\">\r\n");
      out.write("            <h1 align=\"Right\">\r\n");
      out.write("                <img src=\"");
      out.print(ORSView.APP_CONTEXT);
      out.write("/img/rays.png\" width=\"318\"\r\n");
      out.write("                    height=\"90\">\r\n");
      out.write("            </h1>\r\n");
      out.write("        </td>\r\n");
      out.write("\r\n");
      out.write("    </tr>\r\n");
      out.write("    \r\n");
      out.write("    <tr>\r\n");
      out.write("        <td >\r\n");
      out.write("            <h3>\r\n");
      out.write("                ");
      out.print(welcomeMsg);
      out.write("</h3>\r\n");
      out.write("        </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    ");

        if (userLoggedIn) {
        	 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td colspan=\"2\" >\r\n");
      out.write("        \r\n");
      out.write("        <a href=\"");
      out.print(ORSView.GET_MARKSHEET_CTL);
      out.write("\">Get Marksheet</b></a> |\r\n");
      out.write("            <a href=\"");
      out.print(ORSView.MARKSHEET_MERIT_LIST_CTL);
      out.write("\">Marksheet Merit\r\n");
      out.write("                List</b>\r\n");
      out.write("        </a> | <a href=\"");
      out.print(ORSView.MY_PROFILE_CTL);
      out.write("\">MyProfile</b></a> | <a\r\n");
      out.write("            href=\"");
      out.print(ORSView.CHANGE_PASSWORD_CTL);
      out.write("\">Change Password</b></a> | <a\r\n");
      out.write("            href=\"");
      out.print(ORSView.JAVA_DOC_VIEW);
      out.write("\">Java Doc</b></a> | \r\n");
      out.write("   \r\n");
      out.write("            ");

            
            if (userBean.getRoleId() == RoleBean.ADMIN) 
            {
        
      out.write(" <a href=\"");
      out.print(ORSView.MARKSHEET_CTL);
      out.write("\">Add Marksheet</b></a> | <a\r\n");
      out.write("            href=\"");
      out.print(ORSView.MARKSHEET_LIST_CTL);
      out.write("\">Marksheet List</b></a> | \r\n");
      out.write("            <a href=\"");
      out.print(ORSView.USER_CTL);
      out.write("\">Add User</b></a> | <a\r\n");
      out.write("            href=\"");
      out.print(ORSView.USER_LIST_CTL);
      out.write("\">User List</b></a> | <a\r\n");
      out.write("            href=\"");
      out.print(ORSView.COLLEGE_CTL);
      out.write("\">Add College</b></a> | <a\r\n");
      out.write("            href=\"");
      out.print(ORSView.COLLEGE_LIST_CTL);
      out.write("\">College List</b></a> | <a\r\n");
      out.write("            href=\"");
      out.print(ORSView.STUDENT_CTL);
      out.write("\">Add Student</b></a> | <a\r\n");
      out.write("            href=\"");
      out.print(ORSView.STUDENT_LIST_CTL);
      out.write("\">Student List</b></a> | <a\r\n");
      out.write("            href=\"");
      out.print(ORSView.ROLE_CTL);
      out.write("\">Add Role</b></a> | <a\r\n");
      out.write("            href=\"");
      out.print(ORSView.ROLE_LIST_CTL);
      out.write("\">Role List</b></a> | \r\n");
      out.write("           <a href=\"");
      out.print(ORSView.COURSES_CTL);
      out.write("\">Add Course</b></a> |\r\n");
      out.write("           <a href=\"");
      out.print(ORSView.COURSES_LIST_CTL );
      out.write("\">Courses List</a>|\r\n");
      out.write("           <a href=\"");
      out.print(ORSView.FACULTY_CTL);
      out.write("\">Add Faculty</b></a> |\r\n");
      out.write("           <a href=\"");
      out.print(ORSView.FACULTY_LIST_CTL );
      out.write("\">Faculty List</a>|\r\n");
      out.write("           <a href=\"");
      out.print(ORSView.SUBJECTS_CTL);
      out.write("\">Add Subjects</b></a> |\r\n");
      out.write("           <a href=\"");
      out.print(ORSView.SUBJECTS_LIST_CTL );
      out.write("\">Subjects List</a>|\r\n");
      out.write("           <a href=\"");
      out.print(ORSView.TIMETABLE_CTL);
      out.write("\">Create Time Table</b></a> |\r\n");
      out.write("           <a href=\"");
      out.print(ORSView.TIMETABLE_LIST_CTL );
      out.write("\">View Time Table</a>|| ");

     }
 
      out.write("</td>\r\n");
      out.write("    \r\n");
      out.write("    </tr>\r\n");
      out.write("    ");

        }
    
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("<hr>");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<body bgcolor=\"Thistle\">\r\n");
      in.co.sunrays.proj4.bean.CoursesBean cBean = null;
      cBean = (in.co.sunrays.proj4.bean.CoursesBean) _jspx_page_context.getAttribute("cBean", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (cBean == null){
        cBean = new in.co.sunrays.proj4.bean.CoursesBean();
        _jspx_page_context.setAttribute("cBean", cBean, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      in.co.sunrays.proj4.bean.TimeTableBean bean = null;
      bean = (in.co.sunrays.proj4.bean.TimeTableBean) _jspx_page_context.getAttribute("bean", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (bean == null){
        bean = new in.co.sunrays.proj4.bean.TimeTableBean();
        _jspx_page_context.setAttribute("bean", bean, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("\t<form action=\"");
      out.print(ORSView.TIMETABLE_LIST_CTL);
      out.write("\" name=\"frm\" method=\"post\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<h1 align=\"center\">Timetable List</h1>\r\n");
      out.write("\t\t<center>\r\n");
      out.write("\t\t<h2>\r\n");
      out.write("\t\t\t<font color=\"red\">");
      out.print(ServletUtility.getErrorMessage(request));
      out.write("</font>\r\n");
      out.write("\t\t\t<font color=\"green\">");
      out.print(ServletUtility.getSuccessMessage(request));
      out.write("</font>\r\n");
      out.write("\t\t</h2>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
List list = ServletUtility.getList(request);
		Integer i = (Integer)request.getAttribute("var");
      out.write('\r');
      out.write('\n');
      out.write('	');
if(list.size()!=0){
      out.write('\r');
      out.write('\n');
      out.write('	');
List courseList = (List)request.getAttribute("courseList"); 
      out.write("\r\n");
      out.write("\t\t<table width=\"100%\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td align=\"center\"><label>Course Name : </label>\r\n");
      out.write("\t\t\t\t\t");
      out.print(HTMLUtility.getList("courseId", String.valueOf(bean.getCourseId()), courseList) );
      out.write("\r\n");
      out.write("\t\t\t\t\t&emsp;<label>Semester : </label>");

							HashMap map = new HashMap();

							map.put("I", "I");
							map.put("II", "II");
							map.put("III", "III");
							map.put("IV", "IV");
							map.put("V", "V");
							map.put("VI", "VI");
							map.put("VII", "VII");
							map.put("VIII", "VIII");

							String htmlList = HTMLUtility.getList("semester", bean.getSemester(), map);
							DataUtility.getString("semester");
						
      out.write(' ');
      out.print(htmlList);
      out.write("\r\n");
      out.write("\t\t\t\t\t&emsp;<label>Subject Name : </label><input type=\"text\"\r\n");
      out.write("\t\t\t\t\tname=\"subjectName\" placeholder=\"Enter Subject Name\"\r\n");
      out.write("\t\t\t\t\tvalue=\"");
      out.print(ServletUtility.getParameter("subjectName", request));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t&emsp;<label>Exam Date : </label><input type=\"text\" name=\"examDate\"\r\n");
      out.write("\t\t\t\t\t\t  placeholder=\"Date Of Exam(Click Here)\" readonly=\"readonly\" id=\"date\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      out.print(ServletUtility.getParameter("examDate", request));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t&emsp;<input style=\"padding: 5px; width: 100px;\" type=\"submit\" name=\"operation\"\r\n");
      out.write("\t\t\t\t\tvalue=\"");
      out.print(TimeTableListCtl.OP_SEARCH);
      out.write("\"> \r\n");
      out.write("\t\t\t\t\t&emsp;<input style=\"padding: 5px; width: 100px;\" type=\"submit\" name=\"operation\"\r\n");
      out.write("\t\t\t\t\tvalue=\"");
      out.print(TimeTableCtl.OP_RESET);
      out.write("\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<table border=\"1\" width=\"100%\" align=\"center\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th style=\"width: 100px\"><input type=\"checkbox\" name=\"chk_all\" onclick=\"checkedAll()\"/>Select All</th>\r\n");
      out.write("\t\t\t\t<th>S.No</th>\r\n");
      out.write("\t\t\t\t<th>Course Name</th>\r\n");
      out.write("\t\t\t\t<th>Subject Name</th>\r\n");
      out.write("\t\t\t\t<th>Semester</th>\r\n");
      out.write("\t\t\t\t<th>Date</th>\r\n");
      out.write("\t\t\t\t<th>Time</th>\r\n");
      out.write("\t\t\t\t<th>Edit</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");

				TimeTableModel model = new TimeTableModel();
				int pageNo = ServletUtility.getPageNo(request);
					int pageSize = ServletUtility.getPageSize(request);
					int index = ((pageNo - 1) * pageSize) + 1;
					
					Iterator<TimeTableBean> it = list.iterator();
					TimeTableBean tbean= null;
					while (it.hasNext()) {
					 tbean = it.next();
			
      out.write("\r\n");
      out.write("\t\t\t<tr align=\"center\">\r\n");
      out.write("\t\t\t\t<td><input type=\"checkbox\" id=\"sid\" name=\"chk_1\" onchange=\"check()\" value=\"");
      out.print(tbean.getId());
      out.write("\"></td>\r\n");
      out.write("                <td>");
      out.print(index++ );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(tbean.getCourseName());
      out.write("\r\n");
      out.write("\t\t\t\t<td>");
      out.print(tbean.getSubjectName());
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(tbean.getSemester());
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print(tbean.getExamDate());
      out.write("\r\n");
      out.write("\t\t\t\t<td>");
      out.print(tbean.getTime());
      out.write("\r\n");
      out.write("\t\t\t\t<td><a href=\"TimeTableCtl?id=");
      out.print(tbean.getId());
      out.write("\">Edit</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");

				}
			
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<table width=\"100%\" align=\"center\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><input style=\"padding: 5px; width: 100px;\" type=\"submit\" name=\"operation\"\r\n");
      out.write("\t\t\t\t\tvalue=\"");
      out.print(TimeTableCtl.OP_PREVIOUS);
      out.write('"');
      out.write(' ');
if (pageNo == 1) {
      out.write("\r\n");
      out.write("\t\t\t\t\tdisabled=\"disabled\" ");
}
      out.write("></td>\r\n");
      out.write("\t\t\t\t<td ><input style=\"padding: 5px; width: 100px;\" type=\"submit\" name=\"operation\"\r\n");
      out.write("\t\t\t\t\tvalue=\"");
      out.print(TimeTableCtl.OP_NEW);
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t<td><input style=\"padding: 5px; width: 100px; margin-right:-85px;\" type=\"submit\" name=\"operation\"\r\n");
      out.write("\t\t\t\t\tvalue=\"");
      out.print(TimeTableCtl.OP_DELETE);
      out.write('"');
      out.write(' ');
if(list.size()==0){ 
      out.write("disabled=\"disabled\"");
} 
      out.write("></td><td></td>\r\n");
      out.write("\t\t\t\t<td align=\"right\"><input style=\"padding: 5px; width: 100px;\" type=\"submit\" name=\"operation\"\r\n");
      out.write("\t\t\t\t\tvalue=\"");
      out.print(TimeTableCtl.OP_NEXT);
      out.write('"');
      out.write(' ');
if (list.size() < pageSize || model.nextPK()-1 == tbean.getId()) {
      out.write("\r\n");
      out.write("\t\t\t\t\tdisabled=\"disabled\" ");
}
      out.write("></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"pageNo\" value=\"");
      out.print(pageNo);
      out.write("\"> <input\r\n");
      out.write("\t\t\ttype=\"hidden\" name=\"pageSize\" value=\"");
      out.print(pageSize);
      out.write("\">\r\n");
      out.write("\t\t\t");
} else{ 
      out.write("\r\n");
      out.write("\t\t\t<input style=\"padding: 5px; width: 100px;\" type=\"submit\" name=\"operation\" value=\"");
      out.print(TimeTableListCtl.OP_BACK);
      out.write("\">\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t</center>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<div id=\"footer\">\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<HR>\r\n");
      out.write("<LEFT>\r\n");
      out.write("    <H3>(c) Copyrights SUNRAYS Technologies</H3>\r\n");
      out.write("    <LEFT>");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
